### ISSUE TITLE
InCites csv structure changed

### ISSUE THREAD

**Issue by mklevanski** [tand826/pubmed_impact_factor_search#5] opened 2022-08-22 09:55 UTC
Dear tand826, 
Thank you for the very useful code. Unfortunately it doesn't work for me. I suspect, that the titles in the csv file at InCites changed meanwhile. Could you eventually help me to get the add on to run?
Thank you very much in advance!
Best regards
Maja

**Comment by tand826** [comment] 2022-08-22 10:35
@mklevanski 
Hi, Maja. Thank you for reaching out.
I think you could not add your csv file to PIFS. If it is the problem, did you see the message "abc.csv might be not available"? If not, could you describe the problem a little more?

The description of the csv is not enough now. After resolving this issue, I would like to update PIFS.

Regards,
Takumi

**Comment by mklevanski** [comment] 2022-08-22 10:51
Hi Takumi,
Thank you for your ultra-fast answer!
I can add the csv file to PIFS. No matter how I adjust the max/min filter I don't get any output after I click "Check". 

![PIFS_nolist](https://user-images.githubusercontent.com/71263486/185903703-fbadee81-886f-41ca-ab88-10b1a3a04ee5.JPG)

I suspect that the column titles have been changed InCites recently and the add on simply cannot import the right columns. You also are not longer able to specify ISSF as an output. 

![jrc](https://user-images.githubusercontent.com/71263486/185903938-bd7cd70a-dda9-43a3-8aff-6bf64797ab80.JPG)

When I had a look into your code I saw that it's searching for columns termed "Full Journal Title" or "Journal Impact Factor", while in the csv table I imported from InCites these parameters are called "Journal name" and "JIF", respectively. 

![csv](https://user-images.githubusercontent.com/71263486/185904126-3d2f1e0a-3057-491b-90d4-1f92d95c7d59.JPG)

I also tried to rename them in the csv, but unfortunately that didn't help.
Best regards
Maja

**Comment by tand826** [comment] 2022-08-22 11:27
As you pointed out, PIFS still searches columns named "Journal Impact Factor" and "Full Journal Title" although InCites exported csv files no longer have them. Just as in the pics above, I could reproduce the problem. Thank you for the additional report!
For now, please change the 2 column names, and add a blank row as follows:
1. Journal name -> Full Journal Title
2. 2021 JIF -> Journal Impact Factor
3. add a blank row to the 2nd. (As a result, your csv file has the column names on the 3rd row.) 

Because chrome extensions are checked by google, it will take a time to publish the updated PIFS. Please be patient for a while.

Regards,
Takumi

*******************
TODO
- hotfix: [getAdditionalQuery()](https://github.com/tand826/pubmed_impact_factor_search/blob/master/popup.js#L212)

**Comment by mklevanski** [comment] 2022-08-22 11:44
![csv2](https://user-images.githubusercontent.com/71263486/185913639-ee0f8a41-c84b-4145-a613-47c2942edd6b.JPG)

**Comment by mklevanski** [comment] 2022-08-22 11:45
Thank you, Takumi,
I tried, but unfortunately it still doesn't work. Do you have an idea of what I did wrong?
Best
Maja

**Comment by tand826** [comment] 2022-08-22 12:05
I'm sorry, Maja. My instruction was not correct.
Do not add the blank row to the 2nd. So you only need to do the following 2 changes:
1. Journal name -> Full Journal Title
2. 2021 JIF -> Journal Impact Factor

Does this work...?

Regards,
Takumi

**Comment by mklevanski** [comment] 2022-08-22 12:12
Yes:), thank you Takumi! 
Best,
Maja

**Comment by tand826** [comment] 2022-08-25 12:30
done: https://github.com/tand826/pubmed_impact_factor_search/commit/73ac36fe301a99e74f2d8ddfea29ce0b21a99db8

If you have any questions, feel free to reopen.

**Closed as completed by tand826** 2022-08-25 12:30 UTC
